/* Daftar Kecamatan/Kelurahan Kota Surabaya + kode pos, dipakai buat
   autofill Kecamatan/Kabupaten-Kota/Provinsi/Kode Pos di form Generus
   begitu admin/guru memilih Kelurahan dari saran ketik (2026-08-29,
   diminta owner) -- HASILNYA TETAP BISA DIEDIT MANUAL, ini cuma tebakan
   awal supaya tidak perlu ketik ulang.

   Nama Kecamatan/Kelurahan disalin dari halaman resmi Pemkot Surabaya
   (pemerintahan.surabaya.go.id/web/kecamatan_kelurahan, 31 kecamatan,
   153 kelurahan). Kode pos halaman itu TIDAK mencantumkan kode pos --
   kode pos diambil dari kompilasi berita (detik.com, "Kode Pos Semua
   Kelurahan di Surabaya") dicocokkan per nama kelurahan. Beberapa
   kelurahan yang ejaannya beda antar sumber (mis. "Gebang Putih" vs
   "Gerbang Putih", "Sidosermo" vs "Sidorsemo") dicocokkan manual --
   kalau ternyata meleset, admin tinggal timpa manual, field ini memang
   dirancang cuma sbg tebakan awal bukan sumber kebenaran tunggal. */

export type WilayahSurabaya = {
  kelurahan: string;
  kecamatan: string;
  kabupaten_kota: string;
  provinsi: string;
  kode_pos: string;
};

const KABUPATEN_KOTA = 'Kota Surabaya';
const PROVINSI = 'Jawa Timur';

/* [kelurahan, kecamatan, kode_pos] -- dipetakan ke WilayahSurabaya di
   bawah supaya daftarnya ringkas dibaca/diaudit. */
const DATA: [string, string, string][] = [
  // Surabaya Selatan
  ['Dukuh Kupang', 'Dukuh Pakis', '60225'],
  ['Dukuh Pakis', 'Dukuh Pakis', '60225'],
  ['Gunung Sari', 'Dukuh Pakis', '60224'],
  ['Pradah Kalikendal', 'Dukuh Pakis', '60226'],
  ['Dukuh Menanggal', 'Gayungan', '60234'],
  ['Gayungan', 'Gayungan', '60235'],
  ['Ketintang', 'Gayungan', '60231'],
  ['Menanggal', 'Gayungan', '60234'],
  ['Jambangan', 'Jambangan', '60232'],
  ['Karah', 'Jambangan', '60232'],
  ['Kebonsari', 'Jambangan', '60233'],
  ['Pagesangan', 'Jambangan', '60233'],
  ['Karang Pilang', 'Karang Pilang', '60221'],
  ['Kebraon', 'Karang Pilang', '60222'],
  ['Kedurus', 'Karang Pilang', '60223'],
  ['Waru Gunung', 'Karang Pilang', '60221'],
  ['Banyu Urip', 'Sawahan', '60254'],
  ['Kupang Krajan', 'Sawahan', '60253'],
  ['Pakis', 'Sawahan', '60256'],
  ['Petemon', 'Sawahan', '60252'],
  ['Putat Jaya', 'Sawahan', '60255'],
  ['Sawahan', 'Sawahan', '60251'],
  ['Babatan', 'Wiyung', '60227'],
  ['Balas Klumprik', 'Wiyung', '60222'],
  ['Jajar Tunggal', 'Wiyung', '60229'],
  ['Wiyung', 'Wiyung', '60228'],
  ['Bendul Merisi', 'Wonocolo', '60239'],
  ['Jemur Wonosari', 'Wonocolo', '60237'],
  ['Margorejo', 'Wonocolo', '60238'],
  ['Sidosermo', 'Wonocolo', '60239'],
  ['Siwalankerto', 'Wonocolo', '60236'],
  ['Darmo', 'Wonokromo', '60241'],
  ['Jagir', 'Wonokromo', '60244'],
  ['Ngagel', 'Wonokromo', '60246'],
  ['Ngagel Rejo', 'Wonokromo', '60245'],
  ['Sawunggaling', 'Wonokromo', '60242'],
  ['Wonokromo', 'Wonokromo', '60243'],
  // Surabaya Timur
  ['Airlangga', 'Gubeng', '60286'],
  ['Baratajaya', 'Gubeng', '60284'],
  ['Gubeng', 'Gubeng', '60281'],
  ['Kertajaya', 'Gubeng', '60282'],
  ['Mojo', 'Gubeng', '60285'],
  ['Pucang Sewu', 'Gubeng', '60283'],
  ['Gunung Anyar', 'Gunung Anyar', '60294'],
  ['Gunung Anyar Tambak', 'Gunung Anyar', '60294'],
  ['Rungkut Menanggal', 'Gunung Anyar', '60293'],
  ['Rungkut Tengah', 'Gunung Anyar', '60293'],
  ['Dukuh Sutorejo', 'Mulyorejo', '60113'],
  ['Kalijudan', 'Mulyorejo', '60114'],
  ['Kalisari', 'Mulyorejo', '60112'],
  ['Kejawan Putih Tambak', 'Mulyorejo', '60112'],
  ['Manyar Sabrangan', 'Mulyorejo', '60116'],
  ['Mulyorejo', 'Mulyorejo', '60115'],
  ['Kalirungkut', 'Rungkut', '60293'],
  ['Kedung Baruk', 'Rungkut', '60298'],
  ['Medokan Ayu', 'Rungkut', '60295'],
  ['Penjaringansari', 'Rungkut', '60297'],
  ['Rungkut Kidul', 'Rungkut', '60293'],
  ['Wonorejo', 'Rungkut', '60296'],
  ['Gebang Putih', 'Sukolilo', '60117'],
  ['Keputih', 'Sukolilo', '60111'],
  ['Klampis Ngasem', 'Sukolilo', '60117'],
  ['Medokan Semampir', 'Sukolilo', '60119'],
  ['Menur Pumpungan', 'Sukolilo', '60118'],
  ['Nginden Jangkungan', 'Sukolilo', '60118'],
  ['Semolowaru', 'Sukolilo', '60119'],
  ['Dukuh Setro', 'Tambaksari', '60138'],
  ['Gading', 'Tambaksari', '60134'],
  ['Kapasmadya Baru', 'Tambaksari', '60137'],
  ['Pacarkeling', 'Tambaksari', '60131'],
  ['Pacarkembang', 'Tambaksari', '60132'],
  ['Ploso', 'Tambaksari', '60133'],
  ['Rangkah', 'Tambaksari', '60135'],
  ['Tambaksari', 'Tambaksari', '60136'],
  ['Kendangsari', 'Tenggilis Mejoyo', '60292'],
  ['Kutisari', 'Tenggilis Mejoyo', '60291'],
  ['Panjang Jiwo', 'Tenggilis Mejoyo', '60299'],
  ['Tenggilis Mejoyo', 'Tenggilis Mejoyo', '60292'],
  // Surabaya Barat
  ['Asem Rowo', 'Asem Rowo', '60182'],
  ['Genting Kalianak', 'Asem Rowo', '60183'],
  ['Tambak Sarioso', 'Asem Rowo', '60184'],
  ['Kandangan', 'Benowo', '60199'],
  ['Romokalisari', 'Benowo', '60192'],
  ['Sememi', 'Benowo', '60198'],
  ['Tambak Oso Wilangun', 'Benowo', '60191'],
  ['Bangkingan', 'Lakarsantri', '60214'],
  ['Jeruk', 'Lakarsantri', '60212'],
  ['Lakarsantri', 'Lakarsantri', '60211'],
  ['Lidah Kulon', 'Lakarsantri', '60213'],
  ['Lidah Wetan', 'Lakarsantri', '60213'],
  ['Sumurwelut', 'Lakarsantri', '60215'],
  ['Babat Jerawat', 'Pakal', '60197'],
  ['Benowo', 'Pakal', '60195'],
  ['Pakal', 'Pakal', '60196'],
  ['Sumber Rejo', 'Pakal', '60192'],
  ['Beringin', 'Sambikerep', '60218'],
  ['Lontar', 'Sambikerep', '60216'],
  ['Made', 'Sambikerep', '60219'],
  ['Sambikerep', 'Sambikerep', '60217'],
  ['Putat Gede', 'Sukomanunggal', '60189'],
  ['Simomulyo', 'Sukomanunggal', '60281'],
  ['Simomulyo Baru', 'Sukomanunggal', '60281'],
  ['Sonokwijenan', 'Sukomanunggal', '60189'],
  ['Sukomanunggal', 'Sukomanunggal', '60188'],
  ['Tanjungsari', 'Sukomanunggal', '60187'],
  ['Balongsari', 'Tandes', '60186'],
  ['Banjar Sugihan', 'Tandes', '60185'],
  ['Karang Poh', 'Tandes', '60186'],
  ['Manukan Kulon', 'Tandes', '60185'],
  ['Manukan Wetan', 'Tandes', '60184'],
  ['Tandes', 'Tandes', '60187'],
  // Surabaya Pusat
  ['Alun-alun Contong', 'Bubutan', '60174'],
  ['Bubutan', 'Bubutan', '60174'],
  ['Gundih', 'Bubutan', '60172'],
  ['Jepara', 'Bubutan', '60171'],
  ['Tembok Dukuh', 'Bubutan', '60173'],
  ['Embong Kaliasin', 'Genteng', '60271'],
  ['Genteng', 'Genteng', '60275'],
  ['Kapasari', 'Genteng', '60273'],
  ['Ketabang', 'Genteng', '60272'],
  ['Peneleh', 'Genteng', '60274'],
  ['Kapasan', 'Simokerto', '60141'],
  ['Sidodadi', 'Simokerto', '60145'],
  ['Simokerto', 'Simokerto', '60143'],
  ['Simolawang', 'Simokerto', '60144'],
  ['Tambakrejo', 'Simokerto', '60142'],
  ['Dr. Soetomo', 'Tegalsari', '60264'],
  ['Kedungdoro', 'Tegalsari', '60261'],
  ['Keputran', 'Tegalsari', '60265'],
  ['Tegalsari', 'Tegalsari', '60262'],
  ['Wonorejo', 'Tegalsari', '60263'],
  // Surabaya Utara
  ['Bulak', 'Bulak', '60124'],
  ['Kedung Cowek', 'Bulak', '60125'],
  ['Kenjeran', 'Bulak', '60123'],
  ['Sukolilo Baru', 'Bulak', '60122'],
  ['Bulak Banteng', 'Kenjeran', '60127'],
  ['Sidotopo Wetan', 'Kenjeran', '60128'],
  ['Tambak Wedi', 'Kenjeran', '60126'],
  ['Tanah Kali Kedinding', 'Kenjeran', '60129'],
  ['Dupak', 'Krembangan', '60179'],
  ['Kemayoran', 'Krembangan', '60176'],
  ['Krembangan Selatan', 'Krembangan', '60175'],
  ['Morokrembangan', 'Krembangan', '60178'],
  ['Perak Barat', 'Krembangan', '60177'],
  ['Bongkaran', 'Pabean Cantian', '60161'],
  ['Krembangan Utara', 'Pabean Cantian', '60163'],
  ['Nyamplungan', 'Pabean Cantian', '60162'],
  ['Tanjung Perak', 'Pabean Cantian', '60165'],
  ['Ampel', 'Semampir', '60151'],
  ['Pegirian', 'Semampir', '60153'],
  ['Sidotopo', 'Semampir', '60152'],
  ['Ujung', 'Semampir', '60155'],
  ['Wonokusumo', 'Semampir', '60154'],
];

export const WILAYAH_SURABAYA: WilayahSurabaya[] = DATA.map(
  ([kelurahan, kecamatan, kode_pos]) => ({
    kelurahan,
    kecamatan,
    kabupaten_kota: KABUPATEN_KOTA,
    provinsi: PROVINSI,
    kode_pos,
  }),
);
