-- =====================================================================
-- 20260914100000_hafalan_doa_pelaksanaan.sql
--
-- Kartu baru "Hafalan Do'a-Do'a Harian" di Pelaksanaan Pembelajaran
-- (guru mobile), diminta owner 2026-09-14: model & mekanik SAMA PERSIS
-- kartu "Hafalan Surat-Surat Al-Qur'an" (migrasi 20260913110000/120000,
-- per santri, per tanggal, sakelar Naik/Tetap) -- BEDA tabel krn ini
-- materi HAFALAN DO'A (bukan surat), jadi kolomnya cuma nama do'a, TANPA
-- kolom ayat (do'a tidak punya rentang ayat). Daftar DO'A yang ditawarkan
-- per kelas mengikuti target kurikulum "Hafalan Do'a-Do'a Harian" --
-- lihat lib/materiHafalanDoa.ts & opsiHafalanDoa di
-- PelaksanaanPembelajaranView.tsx.
--
-- Skema & RLS SALINAN PERSIS hafalan_surat_pelaksanaan (yang badan
-- kebijakannya sendiri sudah disalin dari PRODUKSI 2026-09-13): guru
-- kelas sendiri (guru_id ATAU guru_id_2), admin_kelompok/admin_desa
-- se-scope (konsisten KEEMPAT operasi), admin_ppg semua, pengunjung
-- meniru cabang guru (selama pengunjung_masih_berlaku()).
--
-- ⚠️ DELETE POLICY DISERTAKAN SEJAK AWAL (pelajaran dari bug tilawati
-- 2026-09-13 -- migrasi lama BISA tercatat "sudah jalan" padahal tidak).
-- ⚠️ Trigger `pengunjung_jejak_trg` DIPASANG SEJAK AWAL jg (pelajaran dari
-- bug infaq_pengajian 2026-09-12) -- tabel ini dibuka tulis utk pengunjung
-- sejak lahir, jadi harus ikut direset 30 hari.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.hafalan_doa_pelaksanaan (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas_id     bigint NOT NULL REFERENCES public.kelas (id),
  kelompok_id  bigint NOT NULL REFERENCES public.kelompok (id),
  santri_id    bigint NOT NULL REFERENCES public.santri (id),
  tanggal      date NOT NULL,
  doa          text,
  status       text CHECK (status IS NULL OR status IN ('naik', 'tetap')),
  dibuat_oleh  uuid REFERENCES public.profiles (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (santri_id, tanggal)
);
COMMENT ON TABLE public.hafalan_doa_pelaksanaan IS
  'Catatan Hafalan Do''a-Do''a Harian per santri per tanggal (Do''a / Naik|Tetap) -- diisi guru di kartu "Hafalan Do''a-Do''a Harian" pada Pelaksanaan Pembelajaran.';

CREATE INDEX IF NOT EXISTS idx_hafalan_doa_kelas_tanggal
  ON public.hafalan_doa_pelaksanaan (kelas_id, tanggal);

-- kelompok_id selalu ditimpa dari kelas (tidak dipercaya dari klien),
-- pola sama sync_hafalan_surat_kelompok_id.
CREATE OR REPLACE FUNCTION public.sync_hafalan_doa_kelompok_id()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_kelompok_id bigint;
BEGIN
  SELECT kl.kelompok_id INTO v_kelompok_id FROM public.kelas kl WHERE kl.id = NEW.kelas_id;
  IF v_kelompok_id IS NULL THEN
    RAISE EXCEPTION 'hafalan_doa_pelaksanaan.kelas_id % tidak ada di tabel kelas', NEW.kelas_id;
  END IF;
  NEW.kelompok_id = v_kelompok_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_hafalan_doa_sync_kelompok_id ON public.hafalan_doa_pelaksanaan;
CREATE TRIGGER trg_hafalan_doa_sync_kelompok_id
  BEFORE INSERT OR UPDATE OF kelas_id, kelompok_id ON public.hafalan_doa_pelaksanaan
  FOR EACH ROW EXECUTE FUNCTION public.sync_hafalan_doa_kelompok_id();

DROP TRIGGER IF EXISTS trg_hafalan_doa_updated_at ON public.hafalan_doa_pelaksanaan;
CREATE TRIGGER trg_hafalan_doa_updated_at
  BEFORE UPDATE ON public.hafalan_doa_pelaksanaan
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Reset otomatis 30 hari utk pengunjung (fungsi generik sudah ada,
-- migrasi 20260911150000) -- WAJIB dipasang sejak awal, lihat catatan
-- di kepala berkas.
DROP TRIGGER IF EXISTS pengunjung_jejak_trg ON public.hafalan_doa_pelaksanaan;
CREATE TRIGGER pengunjung_jejak_trg AFTER INSERT OR UPDATE ON public.hafalan_doa_pelaksanaan
  FOR EACH ROW EXECUTE FUNCTION public.pengunjung_catat_jejak();

ALTER TABLE public.hafalan_doa_pelaksanaan ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hafalan_doa_select_scoped" ON public.hafalan_doa_pelaksanaan;
CREATE POLICY "hafalan_doa_select_scoped" ON public.hafalan_doa_pelaksanaan
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = hafalan_doa_pelaksanaan.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = hafalan_doa_pelaksanaan.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
      OR ((p.role = 'pengunjung'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))))
           AND public.pengunjung_masih_berlaku())
    ))));

DROP POLICY IF EXISTS "hafalan_doa_insert_guru_admin" ON public.hafalan_doa_pelaksanaan;
CREATE POLICY "hafalan_doa_insert_guru_admin" ON public.hafalan_doa_pelaksanaan
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM (kelompok k JOIN kelas kl ON ((kl.kelompok_id = k.id))) WHERE (kl.id = hafalan_doa_pelaksanaan.kelas_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = ( SELECT kl.kelompok_id FROM kelas kl WHERE (kl.id = hafalan_doa_pelaksanaan.kelas_id))))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
      OR ((p.role = 'pengunjung'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))))
           AND public.pengunjung_masih_berlaku())
    ))));

DROP POLICY IF EXISTS "hafalan_doa_update_guru_admin" ON public.hafalan_doa_pelaksanaan;
CREATE POLICY "hafalan_doa_update_guru_admin" ON public.hafalan_doa_pelaksanaan
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = hafalan_doa_pelaksanaan.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = hafalan_doa_pelaksanaan.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
      OR ((p.role = 'pengunjung'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))))
           AND public.pengunjung_masih_berlaku())
    ))));

DROP POLICY IF EXISTS "hafalan_doa_delete_guru_admin" ON public.hafalan_doa_pelaksanaan;
CREATE POLICY "hafalan_doa_delete_guru_admin" ON public.hafalan_doa_pelaksanaan
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = hafalan_doa_pelaksanaan.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = hafalan_doa_pelaksanaan.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = hafalan_doa_pelaksanaan.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
    ))));

COMMIT;
