-- =====================================================================
-- 20260909160000_jamaah.sql
--
-- Fitur "Penerobos Kelp" (Pnb Kelp) -- data & kehadiran majlis taklim
-- jamaah keluarga/umum. Empat tabel:
--
--   sub_kelp          -- pembagian dalam satu kelompok ("Sub Kelp"), tiap
--                        sub-kelp punya nama. Analog "kelas" pada generus.
--   jamaah            -- data jamaah (mirip santri/guru, tapi dewasa:
--                        tanpa jenjang/kelas ngaji; + pekerjaan, status
--                        dalam keluarga).
--   jamaah_acara      -- satu pertemuan/pengajian (judul + tanggal +
--                        tempat). Kehadiran dicatat PER ACARA.
--   jamaah_kehadiran  -- status hadir/izin/sakit/alpa per jamaah per acara.
--
-- Cakupan akses = satu kelompok. Peran baru 'penerobos' (migrasi
-- 20260909150000 -- WAJIB dijalankan lebih dulu) mengelola penuh
-- kelompoknya; admin_kelompok / admin_desa / admin_ppg ikut bisa (pola
-- persis tabel santri).
--
-- Idempoten: CREATE TABLE/INDEX IF NOT EXISTS, DROP POLICY/TRIGGER IF
-- EXISTS sebelum CREATE. Aman dijalankan ulang.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Tabel
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sub_kelp (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id bigint NOT NULL REFERENCES public.kelompok (id),
  nama        text   NOT NULL,
  keterangan  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS sub_kelp_kelompok_idx
  ON public.sub_kelp (kelompok_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.jamaah (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id         bigint NOT NULL REFERENCES public.kelompok (id),
  sub_kelp_id         bigint REFERENCES public.sub_kelp (id),
  nama                text   NOT NULL,
  nama_panggilan      text,
  gender              public.gender_type,
  tempat_lahir        text,
  tanggal_lahir       date,
  status_keluarga     text,      -- Kepala Keluarga / Istri / Anak Dewasa / Lajang / Umum
  pekerjaan           text,
  pendidikan_terakhir text,
  no_wa               text,
  alamat              text,
  rt                  text,
  rw                  text,
  kelurahan           text,
  kecamatan           text,
  kabupaten_kota      text,
  provinsi            text,
  kode_pos            text,
  catatan             text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  deleted_at          timestamptz
);
CREATE INDEX IF NOT EXISTS jamaah_kelompok_idx
  ON public.jamaah (kelompok_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS jamaah_sub_kelp_idx
  ON public.jamaah (sub_kelp_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.jamaah_acara (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id bigint NOT NULL REFERENCES public.kelompok (id),
  sub_kelp_id bigint REFERENCES public.sub_kelp (id),  -- NULL = gabungan se-kelompok
  judul       text   NOT NULL,
  tanggal     date   NOT NULL,
  tempat      text,
  keterangan  text,
  dibuat_oleh uuid REFERENCES public.profiles (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS jamaah_acara_kelompok_tanggal_idx
  ON public.jamaah_acara (kelompok_id, tanggal DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.jamaah_kehadiran (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acara_id    bigint NOT NULL REFERENCES public.jamaah_acara (id) ON DELETE CASCADE,
  jamaah_id   bigint NOT NULL REFERENCES public.jamaah (id),
  status      public.absensi_status NOT NULL,
  catatan     text,
  dicatat_oleh uuid REFERENCES public.profiles (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (acara_id, jamaah_id)
);
CREATE INDEX IF NOT EXISTS jamaah_kehadiran_acara_idx  ON public.jamaah_kehadiran (acara_id);
CREATE INDEX IF NOT EXISTS jamaah_kehadiran_jamaah_idx ON public.jamaah_kehadiran (jamaah_id);

-- ---------------------------------------------------------------------
-- updated_at (pakai fungsi bersama public.set_updated_at())
-- ---------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_sub_kelp_updated_at        ON public.sub_kelp;
DROP TRIGGER IF EXISTS trg_jamaah_updated_at          ON public.jamaah;
DROP TRIGGER IF EXISTS trg_jamaah_acara_updated_at    ON public.jamaah_acara;
DROP TRIGGER IF EXISTS trg_jamaah_kehadiran_updated_at ON public.jamaah_kehadiran;
CREATE TRIGGER trg_sub_kelp_updated_at        BEFORE UPDATE ON public.sub_kelp        FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_jamaah_updated_at          BEFORE UPDATE ON public.jamaah          FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_jamaah_acara_updated_at    BEFORE UPDATE ON public.jamaah_acara    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_jamaah_kehadiran_updated_at BEFORE UPDATE ON public.jamaah_kehadiran FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------
-- Hak akses tabel (RLS yang membatasi baris; grant ini cuma "boleh
-- menyentuh tabel"). Sama pola tabel santri.
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.sub_kelp, public.jamaah, public.jamaah_acara, public.jamaah_kehadiran
  TO authenticated;
GRANT ALL ON
  public.sub_kelp, public.jamaah, public.jamaah_acara, public.jamaah_kehadiran
  TO service_role;

ALTER TABLE public.sub_kelp         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jamaah           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jamaah_acara     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jamaah_kehadiran ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- RLS
--
-- Pola "mengelola kelompok K" (auth_profile() = InitPlan, dievaluasi
-- sekali per-statement, bukan per-baris -- lihat memory
-- ppg-rls-initplan-jurnal): admin_ppg | admin_desa se-desa |
-- admin_kelompok se-kelompok | penerobos se-kelompok.
--
--   EXISTS (SELECT 1 FROM auth_profile()
--             p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
--           WHERE p.is_active AND (
--                p.role = 'admin_ppg'
--             OR (p.role = 'admin_desa'  AND p.scope_desa_id =
--                   (SELECT k.desa_id FROM kelompok k WHERE k.id = <K>))
--             OR (p.role = 'admin_kelompok' AND p.scope_kelompok_id = <K>)
--             OR (p.role = 'penerobos'      AND p.scope_kelompok_id = <K>)))
--
-- DELETE keras dikunci admin_ppg (hapus biasa = lewat deleted_at / UPDATE),
-- kecuali jamaah_kehadiran yang memang boleh dihapus (batalkan centang).
-- ---------------------------------------------------------------------

-- ============ sub_kelp ============
DROP POLICY IF EXISTS "sub_kelp_select"        ON public.sub_kelp;
DROP POLICY IF EXISTS "sub_kelp_insert"        ON public.sub_kelp;
DROP POLICY IF EXISTS "sub_kelp_update"        ON public.sub_kelp;
DROP POLICY IF EXISTS "sub_kelp_delete_ppg"    ON public.sub_kelp;

CREATE POLICY "sub_kelp_select" ON public.sub_kelp
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = sub_kelp.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = sub_kelp.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = sub_kelp.kelompok_id))));

CREATE POLICY "sub_kelp_insert" ON public.sub_kelp
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = sub_kelp.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = sub_kelp.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = sub_kelp.kelompok_id))));

CREATE POLICY "sub_kelp_update" ON public.sub_kelp
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = sub_kelp.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = sub_kelp.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = sub_kelp.kelompok_id))));

CREATE POLICY "sub_kelp_delete_ppg" ON public.sub_kelp
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND p.role = 'admin_ppg'::text));

-- ============ jamaah ============
DROP POLICY IF EXISTS "jamaah_select"     ON public.jamaah;
DROP POLICY IF EXISTS "jamaah_insert"     ON public.jamaah;
DROP POLICY IF EXISTS "jamaah_update"     ON public.jamaah;
DROP POLICY IF EXISTS "jamaah_delete_ppg" ON public.jamaah;

CREATE POLICY "jamaah_select" ON public.jamaah
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah.kelompok_id))));

CREATE POLICY "jamaah_insert" ON public.jamaah
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah.kelompok_id))));

CREATE POLICY "jamaah_update" ON public.jamaah
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah.kelompok_id))));

CREATE POLICY "jamaah_delete_ppg" ON public.jamaah
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND p.role = 'admin_ppg'::text));

-- ============ jamaah_acara ============
DROP POLICY IF EXISTS "jamaah_acara_select"     ON public.jamaah_acara;
DROP POLICY IF EXISTS "jamaah_acara_insert"     ON public.jamaah_acara;
DROP POLICY IF EXISTS "jamaah_acara_update"     ON public.jamaah_acara;
DROP POLICY IF EXISTS "jamaah_acara_delete_ppg" ON public.jamaah_acara;

CREATE POLICY "jamaah_acara_select" ON public.jamaah_acara
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_acara.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_acara.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_acara.kelompok_id))));

CREATE POLICY "jamaah_acara_insert" ON public.jamaah_acara
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_acara.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_acara.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_acara.kelompok_id))));

CREATE POLICY "jamaah_acara_update" ON public.jamaah_acara
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_acara.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_acara.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_acara.kelompok_id))));

CREATE POLICY "jamaah_acara_delete_ppg" ON public.jamaah_acara
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND p.role = 'admin_ppg'::text));

-- ============ jamaah_kehadiran (cakupan lewat acara) ============
DROP POLICY IF EXISTS "jamaah_kehadiran_select" ON public.jamaah_kehadiran;
DROP POLICY IF EXISTS "jamaah_kehadiran_write"  ON public.jamaah_kehadiran;
DROP POLICY IF EXISTS "jamaah_kehadiran_update" ON public.jamaah_kehadiran;
DROP POLICY IF EXISTS "jamaah_kehadiran_delete" ON public.jamaah_kehadiran;

CREATE POLICY "jamaah_kehadiran_select" ON public.jamaah_kehadiran
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k
              WHERE k.id = (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))
      OR (p.role IN ('admin_kelompok'::text, 'penerobos'::text) AND p.scope_kelompok_id =
            (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))));

CREATE POLICY "jamaah_kehadiran_write" ON public.jamaah_kehadiran
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k
              WHERE k.id = (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))
      OR (p.role IN ('admin_kelompok'::text, 'penerobos'::text) AND p.scope_kelompok_id =
            (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))));

CREATE POLICY "jamaah_kehadiran_update" ON public.jamaah_kehadiran
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k
              WHERE k.id = (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))
      OR (p.role IN ('admin_kelompok'::text, 'penerobos'::text) AND p.scope_kelompok_id =
            (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))));

CREATE POLICY "jamaah_kehadiran_delete" ON public.jamaah_kehadiran
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role IN ('admin_kelompok'::text, 'penerobos'::text) AND p.scope_kelompok_id =
            (SELECT a.kelompok_id FROM public.jamaah_acara a WHERE a.id = jamaah_kehadiran.acara_id)))));

COMMENT ON TABLE public.sub_kelp        IS 'Pembagian dalam satu kelompok utk majlis taklim jamaah (fitur Penerobos Kelp). Analog "kelas" pada generus.';
COMMENT ON TABLE public.jamaah          IS 'Data jamaah majlis taklim (dewasa/keluarga, di atas usia generus). Fitur Penerobos Kelp.';
COMMENT ON TABLE public.jamaah_acara    IS 'Satu pertemuan/pengajian jamaah. Kehadiran dicatat per acara.';
COMMENT ON TABLE public.jamaah_kehadiran IS 'Status kehadiran jamaah per acara (enum absensi_status). Unik per (acara_id, jamaah_id).';

COMMIT;
