-- =====================================================================
-- 20260817110000_drift_privilege_identity_fk.sql
--
-- Lanjutan 20260817095000_drift_kolom_produksi. Berkas itu menutup selisih
-- NAMA KOLOM; audit 2026-08-17 berikutnya membandingkan aspek yang belum
-- pernah dicek sama sekali: default value, NOT NULL, tipe/presisi, identity,
-- GRANT tabel/sequence/fungsi, default privileges, dan action FK.
--
-- Hasil audit (produksi fnhqtkqswxsqmjxynldg vs test qaqhoibxcotjzgxdthfl):
--   - default value, NOT NULL, tipe & presisi kolom : 0 selisih
--   - enum, trigger, RLS enabled, policy, owner tabel: 0 selisih
--   - view, publication, replica identity, komentar  : 0 selisih
--   - index & constraint                             : 1 selisih (FK di bawah)
--   - identity_generation                            : 6 selisih (di bawah)
--   - GRANT anon + default privileges                : selisih menyeluruh
--
-- Ketiga kelompok selisih di bawah semuanya no-op di produksi: yang ditulis
-- di sini adalah keadaan produksi APA ADANYA, supaya DB yang dibangun dari
-- berkas migrasi (project test) benar-benar replika produksi.
-- Idempoten, aman dijalankan ulang.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. GRANT: anon TIDAK boleh menulis
--
-- Produksi: anon = rDxtm (SELECT + TRUNCATE/REFERENCES/TRIGGER/MAINTAIN
-- bawaan), TANPA INSERT/UPDATE/DELETE, pada seluruh 37 tabel.
-- Test    : anon = arwdDxtm (penuh) pada seluruh 37 tabel.
--
-- Sebabnya: default privileges project Supabase baru memberi anon ALL saat
-- CREATE TABLE, dan migrasi 20260813125217 hanya GRANT SELECT ke anon —
-- tidak pernah mencabut yang sudah terlanjur menempel. Di produksi
-- pencabutan itu pernah dilakukan manual, jadi tidak tercatat di mana pun.
--
-- Dampaknya kalau dibiarkan: di test, satu policy yang keliru (mis. USING
-- (true) untuk INSERT) bisa membuat anon menulis — dan tidak akan pernah
-- terlihat sebagai kesalahan yang sama di produksi, karena di produksi
-- GRANT-nya memang tidak ada. Uji RLS di test jadi menguji dunia yang
-- lebih longgar daripada dunia sebenarnya.
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM anon;

-- Sequence: produksi anon tidak punya hak apa pun; authenticated hanya
-- rU (SELECT + USAGE), bukan rwU.
REVOKE ALL    ON ALL SEQUENCES IN SCHEMA public FROM anon;
REVOKE UPDATE ON ALL SEQUENCES IN SCHEMA public FROM authenticated;

-- ---------------------------------------------------------------------
-- 2. DEFAULT PRIVILEGES: berlaku untuk objek yang DIBUAT NANTI
--
-- Tanpa bagian ini, selisih pada bagian 1 akan lahir kembali setiap kali
-- ada tabel/fungsi baru di project test.
--
-- Produksi pg_default_acl (defaclrole = postgres, schema public):
--   TABLES    : postgres=arwdDxtm, anon=rDxtm, authenticated=arwdDxtm, service_role=arwdDxtm
--   SEQUENCES : postgres=rwU, authenticated=rU, service_role=rwU        (anon tidak ada)
--   FUNCTIONS : postgres=X, service_role=X                              (anon & authenticated tidak ada)
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE INSERT, UPDATE, DELETE ON TABLES FROM anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE UPDATE ON SEQUENCES FROM authenticated;

-- Catatan penting supaya tidak salah baca: default privileges produksi TIDAK
-- menyebut anon/authenticated untuk FUNCTIONS, tapi itu BUKAN berarti fungsi
-- baru tertutup untuk anon. EXECUTE untuk PUBLIC tetap melekat (bawaan
-- PostgreSQL), dan anon anggota PUBLIC. Terbukti langsung di produksi:
-- has_function_privilege('anon','public.next_nis_santri()','EXECUTE') = true,
-- lewat entri ACL `=X/postgres`.
-- Jadi aturan praktisnya: setiap fungsi baru yang tidak dimaksudkan untuk
-- publik WAJIB `REVOKE EXECUTE ... FROM PUBLIC` eksplisit di migrasinya —
-- GRANT ke authenticated saja tidak menutup anon. Lihat bagian 5.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated;

-- ---------------------------------------------------------------------
-- 3. IDENTITY: 6 tabel memakai GENERATED BY DEFAULT di produksi
--
-- Berkas 20260805080137 menulis `bigint generated always as identity` untuk
-- SEMUA tabel. Di produksi enam tabel di bawah bernilai BY DEFAULT (attidentity
-- = 'd'), 27 tabel sisanya tetap ALWAYS ('a') — sesuai berkas. Keenamnya
-- persis tabel yang diisi lewat ETL dari Google Sheets dengan id eksplisit;
-- GENERATED ALWAYS menolak id eksplisit (SQLSTATE 428C9), jadi produksi
-- pernah dilonggarkan agar muatan itu bisa masuk.
--
-- Arah penyelarasan sengaja test → produksi, bukan sebaliknya: mengubah
-- produksi ke ALWAYS akan mematahkan setiap penulisan yang menyertakan id.
ALTER TABLE public.absensi  ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.desa     ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.guru     ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.kelompok ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.ppg      ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.santri   ALTER COLUMN id SET GENERATED BY DEFAULT;

-- ---------------------------------------------------------------------
-- 4. FK kurikulum_promes.kelompok_id -> kelompok(id)
--
-- 20260817095000 menambahkan kolomnya, tapi tidak FK-nya. Di produksi
-- constraint ini ada dan tervalidasi, dengan ON UPDATE/ON DELETE NO ACTION
-- (confupdtype/confdeltype = 'a') dan MATCH SIMPLE — sama seperti FK lain
-- di skema ini. ADD CONSTRAINT tidak punya IF NOT EXISTS, jadi dijaga
-- manual supaya idempoten.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'kurikulum_promes_kelompok_id_fkey'
      AND conrelid = 'public.kurikulum_promes'::regclass
  ) THEN
    ALTER TABLE public.kurikulum_promes
      ADD CONSTRAINT kurikulum_promes_kelompok_id_fkey
      FOREIGN KEY (kelompok_id) REFERENCES public.kelompok(id);
  END IF;
END
$$;

-- ---------------------------------------------------------------------
-- 5. EXECUTE fungsi: bersihkan sisa hak yang terlanjur menempel
--
-- Bagian 2 hanya mengatur objek yang dibuat SETELAH ini. Tiga fungsi di
-- bawah sudah terlanjur dibuat di project test saat default privileges-nya
-- masih longgar, jadi hak anon/authenticated-nya harus dicabut manual.
--
-- sync_jurnal_kbm_kelompok_id: selisih nyata dengan produksi — di produksi
-- fungsi ini HANYA punya EXECUTE untuk postgres & service_role. Ini fungsi
-- trigger, tidak pernah dipanggil langsung lewat PostgREST.
-- Dry-run 18 Agt 2026 membuktikan `FROM anon, authenticated` saja TIDAK cukup:
-- has_function_privilege(anon, ...) tetap true karena EXECUTE untuk PUBLIC
-- masih melekat di produksi juga, bukan cuma di test. PUBLIC ikut dicabut.
REVOKE EXECUTE ON FUNCTION public.sync_jurnal_kbm_kelompok_id() FROM PUBLIC, anon, authenticated;

-- tambah_santri & next_nis_santri (dari 20260817100000): PERHATIAN, dua baris
-- di bawah BUKAN penyelarasan ke produksi — ini pengetatan yang MENGUBAH
-- produksi, jadi butuh persetujuan terpisah sebelum dipasang di sana.
-- Keadaan produksi 2026-08-17 setelah 20260817100000 dipasang di sana:
-- kedua fungsi punya `=X/postgres` (PUBLIC), sehingga anon — pengunjung
-- tanpa login — bisa memanggil keduanya lewat PostgREST.
--   * tambah_santri: SECURITY INVOKER, jadi anon tetap mentok di GRANT tabel
--     (anon tidak punya INSERT pada santri) — tidak ada jalur tulis.
--   * next_nis_santri: SECURITY DEFINER, jalan sebagai postgres. Anon bisa
--     memanggilnya untuk mengetahui NIS berikutnya (membocorkan berapa
--     banyak santri terdaftar) dan menahan advisory lock.
-- Keduanya tidak pernah dimaksudkan publik: pemanggilnya hanya admin yang
-- sudah login.
REVOKE EXECUTE ON FUNCTION public.tambah_santri(jsonb)  FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.next_nis_santri()     FROM PUBLIC, anon;

COMMIT;
