-- =====================================================================
-- 20260911180000_infaq_pengajian.sql
--
-- Fitur "Infaq Pengajian" (diusulkan seorang guru, 2026-09-11) -- catatan
-- infaq TERKUMPUL GLOBAL per kelas per tanggal (BUKAN per santri, beda
-- dari Tabungan yang per-anak). Owner memutuskan: fitur berdiri sendiri,
-- disatukan dgn Tabungan di balik menu baru "Keuangan" (bukan dimasukkan
-- ke dalam Tabungan -- model datanya beda: Tabungan wajib santri_id,
-- Infaq justru TANPA atribusi ke anak).
--
-- Satu tabel saja: infaq_pengajian (kelas_id + tanggal + jumlah +
-- keterangan). Pola akses SAMA PERSIS jurnal_materi (guru kelas sendiri
-- via guru_id/guru_id_2 -- termasuk guru gilir kedua; admin_kelompok/
-- admin_desa/admin_ppg se-scope; pengunjung meniru cabang guru).
-- Koreksi salah input pakai soft-delete (UPDATE deleted_at), tidak ada
-- DELETE keras -- konsisten dgn jurnal_materi.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.infaq_pengajian (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id  bigint NOT NULL REFERENCES public.kelompok (id),
  kelas_id     bigint NOT NULL REFERENCES public.kelas (id),
  tanggal      date   NOT NULL,
  jumlah       integer NOT NULL CHECK (jumlah >= 0),
  keterangan   text,
  dicatat_oleh uuid REFERENCES public.profiles (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  deleted_at   timestamptz
);
CREATE INDEX IF NOT EXISTS infaq_pengajian_kelas_tanggal_idx
  ON public.infaq_pengajian (kelas_id, tanggal DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS infaq_pengajian_kelompok_tanggal_idx
  ON public.infaq_pengajian (kelompok_id, tanggal DESC) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_infaq_pengajian_updated_at ON public.infaq_pengajian;
CREATE TRIGGER trg_infaq_pengajian_updated_at
  BEFORE UPDATE ON public.infaq_pengajian
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

GRANT SELECT, INSERT, UPDATE ON public.infaq_pengajian TO authenticated;
GRANT ALL ON public.infaq_pengajian TO service_role;

ALTER TABLE public.infaq_pengajian ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "infaq_pengajian_select_scoped" ON public.infaq_pengajian;
CREATE POLICY "infaq_pengajian_select_scoped" ON public.infaq_pengajian
  AS PERMISSIVE FOR SELECT TO public
  USING (
    (( SELECT p.role FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = 'admin_ppg'::text)
    OR ((( SELECT p.role FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = 'admin_desa'::text)
        AND (( SELECT p.scope_desa_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active)
             = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = infaq_pengajian.kelompok_id))))
    OR ((( SELECT p.role FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = 'admin_kelompok'::text)
        AND (( SELECT p.scope_kelompok_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = infaq_pengajian.kelompok_id))
    OR (infaq_pengajian.kelas_id IN ( SELECT kl.id FROM kelas kl
        WHERE ((( SELECT p.guru_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = kl.guru_id)
            OR (( SELECT p.guru_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = kl.guru_id_2))))
    OR ((( SELECT p.role FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = 'pengunjung'::text)
        AND (infaq_pengajian.kelas_id IN ( SELECT kl.id FROM kelas kl
            WHERE ((( SELECT p.guru_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = kl.guru_id)
                OR (( SELECT p.guru_id FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active) WHERE p.is_active) = kl.guru_id_2))))
        AND public.pengunjung_masih_berlaku())
  );

DROP POLICY IF EXISTS "infaq_pengajian_insert_guru_admin" ON public.infaq_pengajian;
CREATE POLICY "infaq_pengajian_insert_guru_admin" ON public.infaq_pengajian
  AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = infaq_pengajian.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = infaq_pengajian.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = infaq_pengajian.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
      OR ((p.role = 'pengunjung'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = infaq_pengajian.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))))
           AND public.pengunjung_masih_berlaku())
    ))));

DROP POLICY IF EXISTS "infaq_pengajian_update_guru_admin" ON public.infaq_pengajian;
CREATE POLICY "infaq_pengajian_update_guru_admin" ON public.infaq_pengajian
  AS PERMISSIVE FOR UPDATE TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = infaq_pengajian.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = infaq_pengajian.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = infaq_pengajian.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2))))))
      OR ((p.role = 'pengunjung'::text) AND (p.guru_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM kelas kl
           WHERE ((kl.id = infaq_pengajian.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))))
           AND public.pengunjung_masih_berlaku())
    ))));

COMMIT;
