-- =====================================================================
-- 20260910150000_jamaah_pengurus.sql
--
-- Fitur "Penerobos Kelp" > menu "Data Pengurus": daftar pengurus
-- (susunan kepengurusan) majlis taklim jamaah.
--
--   jamaah_pengurus
--     - kelompok_id  : cakupan akses (satu kelompok penerobos)
--     - sub_kelp_id  : NULL = pengurus TINGKAT KELOMPOK; terisi = pengurus
--                      milik Sub Kelp itu. (owner: "per kelompok punya
--                      pengurus sendiri, per sub kelp juga")
--     - jamaah_id    : orangnya DIPILIH dari Data Jamaah (bukan ketik nama)
--     - jabatan      : KETIK BEBAS (Ketua / Sekretaris / Bendahara / Seksi …)
--
-- RLS & pola persis tabel `jamaah` (migrasi 20260909160000): admin_ppg |
-- admin_desa se-desa | admin_kelompok se-kelompok | penerobos se-kelompok.
-- Hapus normal = soft-delete via deleted_at (UPDATE). DELETE keras dikunci
-- admin_ppg.
--
-- Idempoten: CREATE ... IF NOT EXISTS, DROP POLICY/TRIGGER IF EXISTS.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.jamaah_pengurus (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id    bigint NOT NULL REFERENCES public.kelompok (id),
  sub_kelp_id    bigint REFERENCES public.sub_kelp (id),
  jamaah_id      bigint NOT NULL REFERENCES public.jamaah (id),
  jabatan        text   NOT NULL,
  urutan         integer NOT NULL DEFAULT 0,
  mulai_menjabat date,
  keterangan     text,
  dicatat_oleh   uuid REFERENCES public.profiles (id),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  deleted_at     timestamptz
);
CREATE INDEX IF NOT EXISTS jamaah_pengurus_kelompok_idx
  ON public.jamaah_pengurus (kelompok_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS jamaah_pengurus_sub_kelp_idx
  ON public.jamaah_pengurus (sub_kelp_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS jamaah_pengurus_jamaah_idx
  ON public.jamaah_pengurus (jamaah_id) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_jamaah_pengurus_updated_at ON public.jamaah_pengurus;
CREATE TRIGGER trg_jamaah_pengurus_updated_at
  BEFORE UPDATE ON public.jamaah_pengurus
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

GRANT SELECT, INSERT, UPDATE, DELETE ON public.jamaah_pengurus TO authenticated;
GRANT ALL ON public.jamaah_pengurus TO service_role;

ALTER TABLE public.jamaah_pengurus ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "jamaah_pengurus_select"     ON public.jamaah_pengurus;
DROP POLICY IF EXISTS "jamaah_pengurus_insert"     ON public.jamaah_pengurus;
DROP POLICY IF EXISTS "jamaah_pengurus_update"     ON public.jamaah_pengurus;
DROP POLICY IF EXISTS "jamaah_pengurus_delete_ppg" ON public.jamaah_pengurus;

CREATE POLICY "jamaah_pengurus_select" ON public.jamaah_pengurus
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_pengurus.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id))));

CREATE POLICY "jamaah_pengurus_insert" ON public.jamaah_pengurus
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_pengurus.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id))));

CREATE POLICY "jamaah_pengurus_update" ON public.jamaah_pengurus
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND (
         p.role = 'admin_ppg'::text
      OR (p.role = 'admin_desa'::text AND p.scope_desa_id =
            (SELECT k.desa_id FROM public.kelompok k WHERE k.id = jamaah_pengurus.kelompok_id))
      OR (p.role = 'admin_kelompok'::text AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id)
      OR (p.role = 'penerobos'::text      AND p.scope_kelompok_id = jamaah_pengurus.kelompok_id))));

CREATE POLICY "jamaah_pengurus_delete_ppg" ON public.jamaah_pengurus
  AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE p.is_active AND p.role = 'admin_ppg'::text));

COMMENT ON TABLE public.jamaah_pengurus IS
  'Susunan kepengurusan majlis taklim jamaah (fitur Penerobos Kelp > Data Pengurus). sub_kelp_id NULL = pengurus tingkat kelompok; terisi = pengurus Sub Kelp itu. jamaah_id dipilih dari tabel jamaah. jabatan ketik bebas. Hapus normal = deleted_at.';

COMMIT;
