-- =====================================================================
-- 20260818120000_jadwal_kbm_identity.sql
--
-- MASALAH: `jadwal_kbm.id` bertipe bigint NOT NULL tetapi TIDAK punya
-- identity maupun default. Selama ini tidak ketahuan karena satu-satunya
-- penulisnya adalah ETL, yang selalu mengisi id secara eksplisit. Begitu
-- aplikasi menulis lewat PostgREST tanpa menyebut id, INSERT-nya PASTI
-- gagal:
--   null value in column "id" of relation "jadwal_kbm" violates not-null
--
-- Ditemukan 18 Agt 2026 saat menguji jalur tulis halaman Jadwal KBM dengan
-- peniruan role di produksi — bukan dari membaca skema, karena kolomnya
-- tampak wajar ("id bigint NOT NULL") sampai benar-benar dicoba diisi.
--
-- Dua tabel lain di produksi juga tidak punya identity pada `id`:
--   * `profiles.id`  — memang disengaja, uuid yang mengacu auth.users.
--   * `hari`         — tabel referensi, 0 baris, belum ada penulisnya.
-- Keduanya SENGAJA tidak disentuh di sini: yang pertama benar apa adanya,
-- yang kedua belum jadi masalah dan perbaikannya bisa menyusul bersama
-- fitur yang memakainya.
--
-- BENTUK PERBAIKAN: BY DEFAULT, bukan ALWAYS — sama seperti enam tabel
-- lain yang diisi ETL (lihat 20260817110000_drift_privilege_identity_fk.sql
-- bagian 3). GENERATED ALWAYS akan menolak id eksplisit dan mematahkan ETL
-- kalau suatu saat dijalankan ulang.
--
-- Sequence-nya dimulai dari max(id)+1 supaya baris yang sudah ada (id 1-10)
-- tidak bentrok dengan baris baru.
--
-- Idempoten: aman dijalankan ulang.
-- =====================================================================

BEGIN;

DO $$
DECLARE mulai bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
     WHERE attrelid = 'public.jadwal_kbm'::regclass
       AND attname = 'id'
       AND attidentity <> ''
  ) THEN
    SELECT coalesce(max(id), 0) + 1 INTO mulai FROM public.jadwal_kbm;
    EXECUTE format(
      'ALTER TABLE public.jadwal_kbm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      mulai
    );
  END IF;
END
$$;

COMMIT;
