-- =====================================================================
-- 20260911190000_shodaqoh.sql
--
-- Fitur "Shodaqoh" (2026-09-11, di bawah menu Keuangan, setelah Infaq
-- Pengajian). Jenis BEBAS diatur admin_kelompok (bisa tambah/ubah/
-- nonaktifkan sendiri) -- owner beri contoh: "Shodaqoh Generus Sakit",
-- "Shodaqoh Guru Sakit", "Shodaqoh Generus Khitan", "Shodaqoh Tali Asih
-- Guru", tapi TIDAK dikunci ke daftar itu.
--
-- Owner memutuskan (2 pertanyaan klarifikasi):
--   1. Granularitas per JENIS, bukan seragam semua: tiap jenis punya
--      `mode` sendiri -- 'per_santri' (siapa nyumbang berapa, pola sama
--      tabungan_transaksi) ATAU 'global' (total terkumpul per kelas per
--      tanggal, pola sama infaq_pengajian).
--   2. Penghimpun Shodaqoh TERPISAH dari penghimpun Tabungan -- kolam
--      uang beda, bisa ditunjuk guru yang berbeda.
--
-- 4 tabel (pola SAMA PERSIS Tabungan, cuma TANPA arah 'tarik' -- shodaqoh
-- searah masuk, tidak ada mekanisme tarik-kembali spt tabungan):
--   shodaqoh_jenis       -- nama + mode, admin_kelompok kelola penuh.
--   shodaqoh_penghimpun  -- 1 baris per kelompok (kolam terpisah dari
--                           tabungan_penghimpun).
--   shodaqoh_setoran     -- guru serahkan himpunannya ke penghimpun.
--   shodaqoh_transaksi   -- satu baris kontribusi. mode 'per_santri' ->
--                           santri_id WAJIB; mode 'global' -> santri_id
--                           NULL, kelas_id opsional (NULL = se-kelompok).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Tabel
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.shodaqoh_jenis (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id  bigint NOT NULL REFERENCES public.kelompok (id),
  nama         text   NOT NULL,
  mode         text   NOT NULL CHECK (mode IN ('per_santri', 'global')),
  urutan       int    NOT NULL DEFAULT 99,
  aktif        boolean NOT NULL DEFAULT true,
  dibuat_oleh  uuid REFERENCES public.profiles (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS shodaqoh_jenis_kelompok_idx
  ON public.shodaqoh_jenis (kelompok_id) WHERE aktif = true;

CREATE TABLE IF NOT EXISTS public.shodaqoh_penghimpun (
  kelompok_id  bigint PRIMARY KEY REFERENCES public.kelompok (id),
  guru_id      bigint REFERENCES public.guru (id),
  catatan      text,
  updated_oleh uuid REFERENCES public.profiles (id),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.shodaqoh_setoran (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id  bigint NOT NULL REFERENCES public.kelompok (id),
  guru_id      bigint NOT NULL REFERENCES public.guru (id),
  jumlah       integer NOT NULL CHECK (jumlah >= 0),
  tanggal      date NOT NULL,
  keterangan   text,
  dicatat_oleh uuid REFERENCES public.profiles (id),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS shodaqoh_setoran_kelompok_idx
  ON public.shodaqoh_setoran (kelompok_id, tanggal DESC);

CREATE TABLE IF NOT EXISTS public.shodaqoh_transaksi (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelompok_id  bigint NOT NULL REFERENCES public.kelompok (id),
  jenis_id     bigint NOT NULL REFERENCES public.shodaqoh_jenis (id),
  kelas_id     bigint REFERENCES public.kelas (id),   -- NULL = se-kelompok (mode global)
  santri_id    bigint REFERENCES public.santri (id),  -- WAJIB kalau jenis.mode = 'per_santri'
  jumlah       integer NOT NULL CHECK (jumlah >= 0),
  tanggal      date NOT NULL,
  keterangan   text,
  setoran_id   bigint REFERENCES public.shodaqoh_setoran (id) ON DELETE SET NULL,
  dicatat_oleh uuid REFERENCES public.profiles (id),
  dicatat_guru_id bigint REFERENCES public.guru (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  deleted_at   timestamptz
);
CREATE INDEX IF NOT EXISTS shodaqoh_transaksi_kelompok_idx
  ON public.shodaqoh_transaksi (kelompok_id, tanggal DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS shodaqoh_transaksi_santri_idx
  ON public.shodaqoh_transaksi (santri_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS shodaqoh_transaksi_setoran_idx
  ON public.shodaqoh_transaksi (setoran_id);

DROP TRIGGER IF EXISTS trg_shodaqoh_jenis_updated_at ON public.shodaqoh_jenis;
CREATE TRIGGER trg_shodaqoh_jenis_updated_at
  BEFORE UPDATE ON public.shodaqoh_jenis
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------
-- Helper: siapa penghimpun Shodaqoh -- SECURITY DEFINER, kolam TERPISAH
-- dari adalah_penghimpun() milik Tabungan (jangan disatukan).
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.adalah_penghimpun_shodaqoh(p_kelompok_id bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = 'public'
AS $$
  SELECT EXISTS (
    SELECT 1
      FROM public.shodaqoh_penghimpun sp,
           auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
     WHERE sp.kelompok_id = p_kelompok_id
       AND sp.guru_id IS NOT NULL
       AND p.is_active
       AND p.role = 'guru'
       AND p.guru_id = sp.guru_id
       AND p.scope_kelompok_id = p_kelompok_id
  )
$$;
REVOKE ALL ON FUNCTION public.adalah_penghimpun_shodaqoh(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.adalah_penghimpun_shodaqoh(bigint) TO authenticated;

-- ---------------------------------------------------------------------
-- Hak akses tabel
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.shodaqoh_jenis, public.shodaqoh_penghimpun, public.shodaqoh_setoran, public.shodaqoh_transaksi
  TO authenticated;
GRANT ALL ON
  public.shodaqoh_jenis, public.shodaqoh_penghimpun, public.shodaqoh_setoran, public.shodaqoh_transaksi
  TO service_role;

ALTER TABLE public.shodaqoh_jenis      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shodaqoh_penghimpun ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shodaqoh_setoran    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shodaqoh_transaksi  ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- RLS -- pola disalin dari tabungan_jenis/tabungan_penghimpun/
-- tabungan_setoran/tabungan_transaksi (lihat pg_policies produksi),
-- disesuaikan nama tabel + tanpa cabang 'tarik' (tidak ada di Shodaqoh).
-- ---------------------------------------------------------------------

-- shodaqoh_jenis: admin_ppg/admin_desa/admin_kelompok/guru boleh baca;
-- HANYA admin yang boleh tulis (tambah/ubah/nonaktifkan jenis).
DROP POLICY IF EXISTS "shodaqoh_jenis_select_scoped" ON public.shodaqoh_jenis;
CREATE POLICY "shodaqoh_jenis_select_scoped" ON public.shodaqoh_jenis
  AS PERMISSIVE FOR SELECT TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_jenis.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_jenis.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.scope_kelompok_id = shodaqoh_jenis.kelompok_id))
    ))));

DROP POLICY IF EXISTS "shodaqoh_jenis_tulis_admin" ON public.shodaqoh_jenis;
CREATE POLICY "shodaqoh_jenis_tulis_admin" ON public.shodaqoh_jenis
  AS PERMISSIVE FOR ALL TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_jenis.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_jenis.kelompok_id))
    ))))
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_jenis.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_jenis.kelompok_id))
    ))));

-- shodaqoh_penghimpun: sama pola (baca 4 peran, tulis admin saja).
DROP POLICY IF EXISTS "shodaqoh_penghimpun_select_scoped" ON public.shodaqoh_penghimpun;
CREATE POLICY "shodaqoh_penghimpun_select_scoped" ON public.shodaqoh_penghimpun
  AS PERMISSIVE FOR SELECT TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_penghimpun.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_penghimpun.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.scope_kelompok_id = shodaqoh_penghimpun.kelompok_id))
    ))));

DROP POLICY IF EXISTS "shodaqoh_penghimpun_tulis_admin" ON public.shodaqoh_penghimpun;
CREATE POLICY "shodaqoh_penghimpun_tulis_admin" ON public.shodaqoh_penghimpun
  AS PERMISSIVE FOR ALL TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_penghimpun.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_penghimpun.kelompok_id))
    ))))
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_penghimpun.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_penghimpun.kelompok_id))
    ))));

-- shodaqoh_setoran: baca 4 peran; INSERT admin ATAU guru menyetor
-- punyanya sendiri; DELETE admin ATAU guru pencatatnya sendiri (FK
-- ON DELETE SET NULL -> transaksi yg sempat masuk kembali "belum setor").
DROP POLICY IF EXISTS "shodaqoh_setoran_select_scoped" ON public.shodaqoh_setoran;
CREATE POLICY "shodaqoh_setoran_select_scoped" ON public.shodaqoh_setoran
  AS PERMISSIVE FOR SELECT TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_setoran.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_setoran.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.scope_kelompok_id = shodaqoh_setoran.kelompok_id))
    ))));

DROP POLICY IF EXISTS "shodaqoh_setoran_insert" ON public.shodaqoh_setoran;
CREATE POLICY "shodaqoh_setoran_insert" ON public.shodaqoh_setoran
  AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_setoran.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_setoran.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.guru_id = shodaqoh_setoran.guru_id) AND (p.scope_kelompok_id = shodaqoh_setoran.kelompok_id))
    ))));

DROP POLICY IF EXISTS "shodaqoh_setoran_delete" ON public.shodaqoh_setoran;
CREATE POLICY "shodaqoh_setoran_delete" ON public.shodaqoh_setoran
  AS PERMISSIVE FOR DELETE TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_setoran.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_setoran.kelompok_id))
      OR ((p.role = 'guru'::text) AND (shodaqoh_setoran.dicatat_oleh = ( SELECT auth.uid() )))
    ))));

-- shodaqoh_transaksi: baca -- 4 peran, se-kelompok (SEMUA transaksi
-- kelompok, bukan cuma kelasnya sendiri -- sama pola tabungan_transaksi,
-- supaya guru bisa lihat riwayat kelompok kalau perlu).
DROP POLICY IF EXISTS "shodaqoh_transaksi_select_scoped" ON public.shodaqoh_transaksi;
CREATE POLICY "shodaqoh_transaksi_select_scoped" ON public.shodaqoh_transaksi
  AS PERMISSIVE FOR SELECT TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_transaksi.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id))
    ))));

-- INSERT: admin bebas; guru boleh kalau --
--   mode per_santri (santri_id terisi): dia guru kelas santri itu
--     (termasuk guru gilir kedua) ATAU dia penghimpun Shodaqoh (cara 2,
--     langsung ke penghimpun tanpa lewat guru kelas -- sama pola
--     tabungan cara 2).
--   mode global (santri_id NULL): kelas_id NULL (se-kelompok, guru
--     mana pun di kelompok itu boleh) ATAU kelas_id terisi & dia guru
--     kelas itu.
DROP POLICY IF EXISTS "shodaqoh_transaksi_insert" ON public.shodaqoh_transaksi;
CREATE POLICY "shodaqoh_transaksi_insert" ON public.shodaqoh_transaksi
  AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_transaksi.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id))
      OR ((p.role = 'guru'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id) AND (
           (shodaqoh_transaksi.santri_id IS NOT NULL AND (
             EXISTS ( SELECT 1 FROM santri s JOIN kelas k ON (k.id = s.kelas_id)
               WHERE (s.id = shodaqoh_transaksi.santri_id) AND ((p.guru_id = k.guru_id) OR (p.guru_id = k.guru_id_2)) AND (k.deleted_at IS NULL))
             OR public.adalah_penghimpun_shodaqoh(shodaqoh_transaksi.kelompok_id)
           ))
        OR (shodaqoh_transaksi.santri_id IS NULL AND (
             shodaqoh_transaksi.kelas_id IS NULL
             OR EXISTS ( SELECT 1 FROM kelas kl
               WHERE (kl.id = shodaqoh_transaksi.kelas_id) AND ((p.guru_id = kl.guru_id) OR (p.guru_id = kl.guru_id_2)))
           ))
      ))
    ))));

-- UPDATE (koreksi/soft-delete): admin bebas; guru cuma barisnya sendiri
-- & SELAMA belum masuk setoran (biar total setoran tidak berubah diam2).
DROP POLICY IF EXISTS "shodaqoh_transaksi_update_admin" ON public.shodaqoh_transaksi;
CREATE POLICY "shodaqoh_transaksi_update_admin" ON public.shodaqoh_transaksi
  AS PERMISSIVE FOR UPDATE TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_transaksi.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id))
    ))))
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (
         (p.role = 'admin_ppg'::text)
      OR ((p.role = 'admin_desa'::text) AND (p.scope_desa_id = ( SELECT k.desa_id FROM kelompok k WHERE (k.id = shodaqoh_transaksi.kelompok_id))))
      OR ((p.role = 'admin_kelompok'::text) AND (p.scope_kelompok_id = shodaqoh_transaksi.kelompok_id))
    ))));

DROP POLICY IF EXISTS "shodaqoh_transaksi_update_guru_sendiri" ON public.shodaqoh_transaksi;
CREATE POLICY "shodaqoh_transaksi_update_guru_sendiri" ON public.shodaqoh_transaksi
  AS PERMISSIVE FOR UPDATE TO public
  USING (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (p.role = 'guru'::text)
      AND (shodaqoh_transaksi.dicatat_oleh = ( SELECT auth.uid() ))
      AND (shodaqoh_transaksi.setoran_id IS NULL))))
  WITH CHECK (EXISTS ( SELECT 1
    FROM auth_profile() p(role, scope_ppg_id, scope_desa_id, scope_kelompok_id, guru_id, is_active)
    WHERE (p.is_active AND (p.role = 'guru'::text)
      AND (shodaqoh_transaksi.dicatat_oleh = ( SELECT auth.uid() ))
      AND (shodaqoh_transaksi.setoran_id IS NULL))));

COMMIT;
